<h1 style="font-size:30px;">Numpy Refresher (Part-3)</h1>

- Element Wise Operations
- Linear Algebra
- Array Statistics


<img src='https://learnopencv.com/wp-content/uploads/2022/01/c4_01_NumPy_logo.png' width=200 align='left'><br/>

In [1]:
import numpy as np

def array_info(array):
    print('Array:\n{}'.format(array))
    print('Data type:\t{}'.format(array.dtype))
    print('Array shape:\t{}'.format(array.shape))
    print('Array Dim:\t{}\n'.format(array.ndim))

## 1 Element-Wise Operations


Let's generate two random arrays to demonstrate element-wise operations. 

In [2]:
a = np.random.random((4,4))
b = np.random.random((4,4))
array_info(a)
array_info(b)

Array:
[[0.09629177 0.55450109 0.64392185 0.02829702]
 [0.48779066 0.23031475 0.3603628  0.23025478]
 [0.2945682  0.38882777 0.64578038 0.88811079]
 [0.56477474 0.36669258 0.68991165 0.62268748]]
Data type:	float64
Array shape:	(4, 4)
Array Dim:	2

Array:
[[0.34909146 0.21049299 0.19914221 0.72521734]
 [0.14459346 0.7118491  0.58959442 0.74651466]
 [0.76618767 0.48089286 0.63497047 0.09638991]
 [0.67960954 0.4928738  0.49374518 0.24422084]]
Data type:	float64
Array shape:	(4, 4)
Array Dim:	2



### 1.1 Element-Wise Scalar Operations

### <font style="color:rgb(50,120,230)">Scalar Addition</font>

In [3]:
a + 5 # Element wise scalar addition.

array([[5.09629177, 5.55450109, 5.64392185, 5.02829702],
       [5.48779066, 5.23031475, 5.3603628 , 5.23025478],
       [5.2945682 , 5.38882777, 5.64578038, 5.88811079],
       [5.56477474, 5.36669258, 5.68991165, 5.62268748]])

### <font style="color:rgb(50,120,230)">Scalar Subtraction</font>

In [4]:
a - 5 # Element wise scalar subtraction.

array([[-4.90370823, -4.44549891, -4.35607815, -4.97170298],
       [-4.51220934, -4.76968525, -4.6396372 , -4.76974522],
       [-4.7054318 , -4.61117223, -4.35421962, -4.11188921],
       [-4.43522526, -4.63330742, -4.31008835, -4.37731252]])

### <font style="color:rgb(50,120,230)">Scalar Multiplication</font>

In [5]:
a * 10 # Element wise scalar multiplication.

array([[0.96291771, 5.54501091, 6.43921849, 0.28297019],
       [4.87790659, 2.30314748, 3.60362797, 2.30254776],
       [2.94568201, 3.88827774, 6.45780384, 8.88110791],
       [5.6477474 , 3.66692582, 6.89911654, 6.2268748 ]])

### <font style="color:rgb(50,120,230)">Scalar Division</font>

In [6]:
a/10 # Element wise scalar division.

array([[0.00962918, 0.05545011, 0.06439218, 0.0028297 ],
       [0.04877907, 0.02303147, 0.03603628, 0.02302548],
       [0.02945682, 0.03888278, 0.06457804, 0.08881108],
       [0.05647747, 0.03666926, 0.06899117, 0.06226875]])

### 1.2 Element-Wise Array Operations

### <font style="color:rgb(50,120,230)">Array Addition</font>

In [7]:
a + b # Element wise array/vector addition.

array([[0.44538323, 0.76499408, 0.84306406, 0.75351436],
       [0.63238412, 0.94216384, 0.94995722, 0.97676943],
       [1.06075587, 0.86972064, 1.28075086, 0.9845007 ],
       [1.24438428, 0.85956638, 1.18365683, 0.86690833]])

### <font style="color:rgb(50,120,230)">Array Subtraction</font>

In [8]:
a - b # Element wise array/vector subtraction.

array([[-0.25279969,  0.3440081 ,  0.44477964, -0.69692032],
       [ 0.3431972 , -0.48153435, -0.22923163, -0.51625988],
       [-0.47161947, -0.09206509,  0.01080991,  0.79172088],
       [-0.1148348 , -0.12618122,  0.19616648,  0.37846664]])

### <font style="color:rgb(50,120,230)">Array Multiplication</font>

In [9]:
a * b # Element wise array/vector multiplication.

array([[0.03361464, 0.11671859, 0.12823202, 0.02052149],
       [0.07053134, 0.16394934, 0.2124679 , 0.17188857],
       [0.22569452, 0.1869845 , 0.41005148, 0.08560492],
       [0.3838263 , 0.18073317, 0.34064055, 0.15207326]])

### <font style="color:rgb(50,120,230)">Array Division</font>

In [10]:
a / b # element wise array/vector division

array([[0.27583536, 2.63429714, 3.23347753, 0.03901867],
       [3.37353202, 0.32354434, 0.61120455, 0.30843973],
       [0.38445959, 0.80855384, 1.01702428, 9.21373216],
       [0.83102827, 0.74398879, 1.39730308, 2.54969014]])

Notice that the dimension of both arrays are equal in the above array element-wise operations. **What if the dimensions are not equal.** Let's check!

In [11]:
print('Array "a":')
array_info(a)
print('Array "c":')
c = np.random.rand(2, 4)
array_info(c)

# Should throw ValueError.
import traceback
try:
    a + c
except Exception:
    traceback.print_exc()

Array "a":
Array:
[[0.09629177 0.55450109 0.64392185 0.02829702]
 [0.48779066 0.23031475 0.3603628  0.23025478]
 [0.2945682  0.38882777 0.64578038 0.88811079]
 [0.56477474 0.36669258 0.68991165 0.62268748]]
Data type:	float64
Array shape:	(4, 4)
Array Dim:	2

Array "c":
Array:
[[0.80631633 0.52453573 0.4349058  0.32539568]
 [0.75653753 0.87034519 0.8745171  0.23847626]]
Data type:	float64
Array shape:	(2, 4)
Array Dim:	2



Traceback (most recent call last):
  File "/var/folders/l6/lv6v6fx914q9jn_l4f9r7nxw0000gn/T/ipykernel_11282/3053537578.py", line 10, in <module>
    a + c
ValueError: operands could not be broadcast together with shapes (4,4) (2,4) 


<font color='red'>**Oh, got the ValueError!!**</font>

What is this error?

<font color='red'>ValueError</font>: operands could not be broadcast together with shapes `(4,4)` `(2,2)` 

### 1.3 Broadcasting

There is a concept of broadcasting in NumPy, which tries to copy rows or columns in the lower-dimensional array to make an equal dimensional array of higher-dimensional array. 

<hr style="border:none; height: 4px; background-color:#D3D3D3" />

Documentation: <a href="https://numpy.org/doc/stable/user/basics.broadcasting.html" target=_blank>broadcasting</a>

When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing (i.e., rightmost) dimensions and works its way left. Two dimensions are compatible when:

 - They are equal, or
 - One of them is 1
 
The examples below show how `B` is successfully broadcasted to `A` according to the rules above.
 
``` python
A      (2d array):  5 x 4
B      (1d array):      1
Result (2d array):  5 x 4

A      (2d array):  5 x 4
B      (1d array):      4
Result (2d array):  5 x 4

A      (3d array):  15 x 3 x 5
B      (3d array):  15 x 1 x 5
Result (3d array):  15 x 3 x 5

A      (3d array):  15 x 3 x 5
B      (2d array):       3 x 5
Result (3d array):  15 x 3 x 5

A      (3d array):  15 x 3 x 5
B      (2d array):       3 x 1
Result (3d array):  15 x 3 x 5
```

<hr style="border:none; height: 4px; background-color:#D3D3D3" />

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6],[7, 8, 9]])
b = np.array([0, 1, 0])

print('Array "a":')
array_info(a)
print('Array "b":')
array_info(b)

print('Array "a+b":')
array_info(a + b)  # b is reshaped such that it can be added to a.

# b = [0,1,0] is broadcasted to     [[0, 1, 0],
#                                    [0, 1, 0],
#                                    [0, 1, 0]]  and added to a.

Array "a":
Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Data type:	int64
Array shape:	(3, 3)
Array Dim:	2

Array "b":
Array:
[0 1 0]
Data type:	int64
Array shape:	(3,)
Array Dim:	1

Array "a+b":
Array:
[[1 3 3]
 [4 6 6]
 [7 9 9]]
Data type:	int64
Array shape:	(3, 3)
Array Dim:	2



## 2 Linear Algebra

In this section, we will take a look at the most commonly used linear algebra operations used in machine learning.

## 2.1 Transpose

<hr style="border:none; height: 4px; background-color:#D3D3D3" />

Either syntax below can be used:

``` python
result = np.transpose(a, axes=None)

result = a.transpose(*axes)

result = a.T
```

Returns a view of the NumPy array `a` with axes transposed.

Documentation: <a href="https://numpy.org/doc/stable/reference/generated/numpy.transpose.html" target=_blank>np.transpose</a>

<hr style="border:none; height: 4px; background-color:#D3D3D3" />


In [ ]:
a = np.random.random((2,3))
print('Array "a":')
array_info(a)

print('Transose of "a":')
a_transpose = a.transpose()  # Or a.T
array_info(a_transpose)

Array "a":
Array:
[[0.89042525 0.00185178 0.63485571]
 [0.45828996 0.39700786 0.74523715]]
Data type:	float64
Array shape:	(2, 3)
Array Dim:	2

Transose of "a":
Array:
[[0.89042525 0.45828996]
 [0.00185178 0.39700786]
 [0.63485571 0.74523715]]
Data type:	float64
Array shape:	(3, 2)
Array Dim:	2



### 2.2 Matrix Multiplication
We will discuss two ways of performing matrix multiplication.

- `np.matmul`
- Python `@` operator

### <font style="color:rgb(50,120,230)">Using: `matmul`</font>

<hr style="border:none; height: 4px; background-color:#D3D3D3" />

Using `matmul` is the most common approach for multiplying two matrices using Numpy. Multiplying two matrices requires that the number of columns of the first matrix, `M`, equals the number of rows in the second matrix, `N`, as shown below.

``` python
   M        N      
[p, q] x [q, r] = [p , r]
```
Documentation: <a href="https://docs.scipy.org/doc/numpy/reference/generated/numpy.matmul.html" target=_blank>np.matmul</a>

<hr style="border:none; height: 4px; background-color:#D3D3D3" />

In [ ]:
a = np.random.random((3, 4))
b = np.random.random((4, 2))

print('Array "a":')
array_info(a)
print('Array "b"')
array_info(b)

# Matrix multiplication of a and b.
c = np.matmul(a,b) 

print('matrix multiplication of a and b:')
array_info(c)

print('{} x {} --> {}'.format(a.shape, b.shape, c.shape)) # dim-1 of a and dim-0 of b has to be 
                                                          # same for matrix multiplication

Array "a":
Array:
[[0.6558135  0.44199714 0.2873197  0.92405359]
 [0.3087299  0.18971711 0.75472795 0.29666377]
 [0.42034068 0.77374161 0.35020636 0.32808625]]
Data type:	float64
Array shape:	(3, 4)
Array Dim:	2

Array "b"
Array:
[[0.7266519  0.41308904]
 [0.26073966 0.53704643]
 [0.76897388 0.10513026]
 [0.55644044 0.62232665]]
Data type:	float64
Array shape:	(4, 2)
Array Dim:	2

matrix multiplication of a and b:
Array:
[[1.32691644 1.11355153]
 [1.01924774 0.49338635]
 [0.95904648 0.8301674 ]]
Data type:	float64
Array shape:	(3, 2)
Array Dim:	2

(3, 4) x (4, 2) --> (3, 2)


### <font style="color:rgb(50,120,230)">Using: `@` operator</font>

This method of multiplication was introduced in Python 3.5. <a href="https://www.python.org/dev/peps/pep-0465/" target=_blank>See docs</a>.

In [ ]:
a = np.random.random((3, 4))
b = np.random.random((4, 2))

print('Array "a":')
array_info(a)
print('Array "b"')
array_info(b)

# Matrix multiplication of a and b.
c = a@b 
array_info(c)

Array "a":
Array:
[[0.91184197 0.99647478 0.71448849 0.97777114]
 [0.30830991 0.53614134 0.82528076 0.89638653]
 [0.57088338 0.53093183 0.48706807 0.81887126]]
Data type:	float64
Array shape:	(3, 4)
Array Dim:	2

Array "b"
Array:
[[0.36932614 0.77824974]
 [0.52367608 0.28492496]
 [0.80329695 0.50109414]
 [0.85338901 0.58182426]]
Data type:	float64
Array shape:	(4, 2)
Array Dim:	2

Array:
[[2.26696265 1.92047829]
 [1.82254324 1.32778495]
 [1.57895448 1.3160717 ]]
Data type:	float64
Array shape:	(3, 2)
Array Dim:	2



### 2.3 Matrix Inverse

<hr style="border:none; height: 4px; background-color:#D3D3D3" />

``` python
np.linalg.inv(a)
```

For a square matrix, `a`, compute the (multiplicative) inverse of a matrix.

Documentation: <a href="https://numpy.org/doc/stable/reference/generated/numpy.linalg.inv.html?highlight=matrix%20inverse" target=_blank>np.linalg.inv</a>

<hr style="border:none; height: 4px; background-color:#D3D3D3" />


In [ ]:
A = np.random.random((3,3))
print('Array "A":')
array_info(A)

A_inverse = np.linalg.inv(A)
print('Inverse of "A" ("A_inverse"):')
array_info(A_inverse)

print('"A x A_inverse = Identity" should be true:')
A_X_A_inverse = np.matmul(A, A_inverse)  # A x A_inverse = I = Identity matrix
array_info(A_X_A_inverse)

Array "A":
Array:
[[0.91980067 0.88840414 0.30798564]
 [0.44189709 0.15825762 0.36623873]
 [0.11574711 0.57521542 0.48989421]]
Data type:	float64
Array shape:	(3, 3)
Array Dim:	2

Inverse of "A" ("A_inverse"):
Array:
[[ 0.65110184  1.26206564 -1.35283764]
 [ 0.85139173 -2.02933564  0.98185457]
 [-1.15350783  2.0845821   1.20803459]]
Data type:	float64
Array shape:	(3, 3)
Array Dim:	2

"A x A_inverse = Identity" should be true:
Array:
[[ 1.00000000e+00  8.50868268e-17 -1.31287266e-16]
 [-9.46459746e-17  1.00000000e+00 -9.00679422e-17]
 [-1.27856568e-17 -2.72579233e-17  1.00000000e+00]]
Data type:	float64
Array shape:	(3, 3)
Array Dim:	2



### 2.4 Dot Product

The dot product between two euqal length vectors is a scalar defined by the sum of the element-wise product of the two vectors.

<hr style="border:none; height: 4px; background-color:#D3D3D3" />

``` python
np.dot(a, b, out=None)
```


Documentation: <a href="https://numpy.org/doc/stable/reference/generated/numpy.dot.html?highlight=dot%20product" target=_blank>np.dot</a>

<hr style="border:none; height: 4px; background-color:#D3D3D3" />


In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

array_info(a)
array_info(b)

dot_prod = np.dot(a, b) 
array_info(dot_prod)

Array:
[1 2 3 4]
Data type:	int64
Array shape:	(4,)
Array Dim:	1

Array:
[5 6 7 8]
Data type:	int64
Array shape:	(4,)
Array Dim:	1

Array:
70
Data type:	int64
Array shape:	()
Array Dim:	0



## 3 Array Statistics

### 3.1 Sum

In [ ]:
a = np.array([1, 2, 3, 4, 5])

print(a.sum())

15


### 3.2 Sum Along Axis

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])
array_info(a)
print('')

print('sum along axis=0: ',a.sum(axis = 0)) # Sum along axis=0 ie: 1+4, 2+5, 3+6
print("")
print('sum along axis=1: ',a.sum(axis = 1)) # Sum along axis=1 ie: 1+2+3, 4+5+6

Array:
[[1 2 3]
 [4 5 6]]
Data type:	int64
Array shape:	(2, 3)
Array Dim:	2


sum along axis=0:  [5 7 9]

sum along axis=1:  [ 6 15]


### 3.3 Minimum and Maximum

In [ ]:
a = np.array([-1.1, 2, 5, 100])

print('Minimum = ', a.min())
print('Maximum = ', a.max())

Minimum =  -1.1
Maximum =  100.0


### 3.4 Min and Max along Axis

In [ ]:
a = np.array([[-2, 0, 4], [1, 2, 3]])

array_info(a)

print('a =\n',a,'\n')
print('Minimum = ', a.min())
print('Maximum = ', a.max())
print()
print('Minimum along axis 0 = ', a.min(0))
print('Maximum along axis 0 = ', a.max(0))
print()
print('Minimum along axis 1 = ', a.min(1))
print('Maximum along axis 1 = ', a.max(1))

Array:
[[-2  0  4]
 [ 1  2  3]]
Data type:	int64
Array shape:	(2, 3)
Array Dim:	2

a =
 [[-2  0  4]
 [ 1  2  3]] 

Minimum =  -2
Maximum =  4

Minimum along axis 0 =  [-2  0  3]
Maximum along axis 0 =  [1 2 4]

Minimum along axis 1 =  [-2  1]
Maximum along axis 1 =  [4 3]


### 3.5 Mean and Standard Deviation

In [ ]:
# Create some data.
data = np.array([1.2, 2.3, 5.0, 3.3, 1.4, 5.6])

print('Mean of the array               = {:8.6f}'.format(data.mean()))
print('Standard deviation of the array = {:8.6f}'.format(data.std()))

Mean of the array               = 3.133333
Standard deviation of the array = 1.684900


### 3.6 Standardizing an Array

Normalize the data array to have `mean=0` and `std=1`.

In [ ]:
print('Array              = ', data)
print('Mean               = {:8.6f}'.format(data.mean()))
print('Standard deviation = {:8.6f}'.format(data.std()))
print()

standardized_array = (data - data.mean())/data.std()

print('Standardized Array = ', standardized_array)
print('Mean               = {:8.6f}'.format(standardized_array.mean()))  
print('Standard deviation = {:8.6f}'.format(standardized_array.std()))   

Array              =  [1.2 2.3 5.  3.3 1.4 5.6]
Mean               = 3.133333
Standard deviation = 1.684900

Standardized Array =  [-1.14744675 -0.49458912  1.10787962  0.09891782 -1.02874536  1.46398379]
Mean               = -0.000000
Standard deviation = 1.000000
